version: "3"

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${BANCO_SENHA}"
      MYSQL_DATABASE: "${BANCO}"
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    volumes:
      - db-atividade-node:/home/matheus/git/Atividades-NodeJs/data
    depends_on:
      - db

volumes:
  db-atividade-node:
